"""auth: display_name, is_archived

Revision ID: 610b7d4ad610
Revises: 56b702ce2307
Create Date: 2026-06-17 10:33:22.349586

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '610b7d4ad610'
down_revision: str | None = '56b702ce2307'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pads', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('pads', 'is_archived')
    # ### end Alembic commands ###
