"""pad display name

Revision ID: 726857c6f636
Revises: 610b7d4ad610
Create Date: 2026-06-17 11:17:44.381496

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '726857c6f636'
down_revision: str | None = '610b7d4ad610'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pads', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pads', 'name')
    # ### end Alembic commands ###
