"""files table

Revision ID: dcd7e589eb1b
Revises: 726857c6f636
Create Date: 2026-06-17 12:48:49.145959

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'dcd7e589eb1b'
down_revision: str | None = '726857c6f636'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pad_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('scan_status', sa.Enum('pending', 'clean', 'failed', name='scan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pad_id'], ['pads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_files_pad_id'), 'files', ['pad_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_files_pad_id'), table_name='files')
    op.drop_table('files')
